### ISSUE TITLE
Bootstrap fails to build with node v12.18.2+

### ISSUE THREAD

**Issue by sfsaccone** [laravel/ui#119]
- UI Version: 2.1.0
- Laravel Version: 7.19
- PHP Version: 7.4.3
- Database Driver & Version: mysql 8.0.20
- nvm: v0.35.3

### Description:

The build step fails with the message:

`Cannot find module '@babel/compat-data/corejs3-shipped-proposals'`

A workaround is to use node v12.16.2.

### Steps To Reproduce:

``` bash
nvm use v12.18.2
php artisan ui bootstrap
npm install && npm run dev # build step
```

### Notes

* It also fails with node v14.5.0. Assuming it fails for v12.18.2 - v14.5.0.
* It works with node v12.16.2
* A similar issue was reported with the node 12.16.2 workaround [here](https://github.com/storybookjs/storybook/issues/10477)
* A similar issue was reported in [JeffreyWay/laravel-mix](https://github.com/JeffreyWay/laravel-mix/issues/2383) with a workaround that might allow later versions of node

I'm new to Laravel and was following the [v7 Frontend Docs](https://laravel.com/docs/7.x/frontend) for this. Should I continue to use node 12.16.2? Or is there another workaround? I found that the vue build also succeeds with 12.16.2, as do the `--auth` builds for bootstrap and vue.

**Comment by driesvints** [comment]
I can run these steps just fine on Node v14.5.0
